on: 
  pull_request:
    branches:
    - staging
    - master
    paths-ignore:
    - 'docs/**'
    - 'scripts/**'
    - 'support/**'
    - '**.md'

jobs:
  run_tests: 
    container: nervesproject/nerves_system_br:latest
    runs-on: ubuntu-18.04
    steps:
    - name: Install Elixir
      run: |
        wget https://repo.hex.pm/builds/elixir/v1.9.0-otp-22.zip
        unzip -d /usr/local/elixir v1.9.0-otp-22.zip
    - name: install mix archives
      run: |
        export PATH=/usr/local/elixir/bin:$PATH
        mix local.hex --force
        mix local.rebar --force
        mix archive.install hex nerves_bootstrap "~> 1.6" --force

  build_deploy_firmware:
    container: nervesproject/nerves_system_br:latest
    runs-on: ubuntu-18.04
    needs: [run_tests]
    steps:
    - name: Install Elixir
      run: |
        wget https://repo.hex.pm/builds/elixir/v1.9.0-otp-22.zip
        unzip -d /usr/local/elixir v1.9.0-otp-22.zip
    - name: install mix archives
      run: |
        export PATH=/usr/local/elixir/bin:$PATH
        mix local.hex --force
        mix local.rebar --force
        mix archive.install hex nerves_bootstrap "~> 1.6" --force
    - name: build firmware
      working-directory: ./farmbot_os
      env:
        MIX_ENV: prod
        MIX_TARGET: rpi3
      run: |
        export PATH=/usr/local/elixir/bin:$PATH
        mix deps.get
        mix compile --force
        mix firmware
    - name: deploy firmware to NervesHub
      working-directory: ./farmbot_os
      env:
        MIX_ENV: prod
        MIX_TARGET: rpi3
        NERVES_HUB_KEY: ${{ secrets.NERVES_HUB_KEY }}
        NERVES_HUB_CERT: ${{ secrets.NERVES_HUB_CERT }}
        NERVES_HUB_FW_PRIVATE_KEY: ${{ secrets.NERVES_HUB_FW_PRIVATE_KEY }}
        NERVES_HUB_FW_PUBLIC_KEY: ${{ secrets.NERVES_HUB_FW_PUBLIC_KEY }}
      run: |
        export PATH=/usr/local/elixir/bin:$PATH
        mix nerves_hub.firmware publish --deploy rpi3-prod-next --tty 3600 _build/rpi3/rpi3_prod/nerves/images/farmbot.fw